# version: '3.7'
# services:
#   db:
#     image: postgres
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     ports:
#       - '5433:5433'
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=mysecretpassword
#       - POSTGRES_DB=mydb
#     restart: always
#     build:
#       context: ./data/db
#       dockerfile: Dockerfile
